#!/bin/bash

clear
echo -e "================================================="
echo -e "#         Premium Auto Script By Horasss        #"
echo -e "#-----------------------------------------------#"
echo -e "# For Debian 9 & Debian 10 64 bit               #"
echo -e "# For Ubuntu 18.04 & Ubuntu 20.04 64 bit        #"
echo -e "# For VPS with KVM and VMWare virtualization    #"
echo -e "# Build Up By HORASSS                           #"
echo -e "#-----------------------------------------------#"
echo -e "# Thanks To                                     #"
echo -e "#-----------------------------------------------#"
echo -e "# HORASSS                                       #"
echo -e "# Jesus Crisht                                  #"
echo -e "# My Family                                     #"
echo -e "# Google                                        #"
echo -e "# Admin Portal & White Vps                      #"
echo -e "# VPNSTORES.NET                                 #"
echo -e "#                                               #"
echo -e "#-----------------------------------------------#"
echo -e "================================================="
